//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.10.23 at 08:50:01 AM PDT
//

package org.openpnp.model.eagle.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "frame")
public class Frame
{

	@XmlAttribute(name = "x1", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String	x1;
	@XmlAttribute(name = "y1", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String	y1;
	@XmlAttribute(name = "x2", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String	x2;
	@XmlAttribute(name = "y2", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String	y2;
	@XmlAttribute(name = "columns", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String	columns;
	@XmlAttribute(name = "rows", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String	rows;
	@XmlAttribute(name = "layer", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String	layer;
	@XmlAttribute(name = "border-left")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String	borderLeft;
	@XmlAttribute(name = "border-top")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String	borderTop;
	@XmlAttribute(name = "border-right")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String	borderRight;
	@XmlAttribute(name = "border-bottom")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String	borderBottom;

	/**
	 * Gets the value of the borderBottom property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getBorderBottom()
	{
		if (this.borderBottom == null)
			return "yes";
		else
			return this.borderBottom;
	}

	/**
	 * Gets the value of the borderLeft property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getBorderLeft()
	{
		if (this.borderLeft == null)
			return "yes";
		else
			return this.borderLeft;
	}

	/**
	 * Gets the value of the borderRight property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getBorderRight()
	{
		if (this.borderRight == null)
			return "yes";
		else
			return this.borderRight;
	}

	/**
	 * Gets the value of the borderTop property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getBorderTop()
	{
		if (this.borderTop == null)
			return "yes";
		else
			return this.borderTop;
	}

	/**
	 * Gets the value of the columns property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getColumns()
	{
		return this.columns;
	}

	/**
	 * Gets the value of the layer property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getLayer()
	{
		return this.layer;
	}

	/**
	 * Gets the value of the rows property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getRows()
	{
		return this.rows;
	}

	/**
	 * Gets the value of the x1 property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getX1()
	{
		return this.x1;
	}

	/**
	 * Gets the value of the x2 property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getX2()
	{
		return this.x2;
	}

	/**
	 * Gets the value of the y1 property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getY1()
	{
		return this.y1;
	}

	/**
	 * Gets the value of the y2 property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getY2()
	{
		return this.y2;
	}

	/**
	 * Sets the value of the borderBottom property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setBorderBottom(String value)
	{
		this.borderBottom = value;
	}

	/**
	 * Sets the value of the borderLeft property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setBorderLeft(String value)
	{
		this.borderLeft = value;
	}

	/**
	 * Sets the value of the borderRight property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setBorderRight(String value)
	{
		this.borderRight = value;
	}

	/**
	 * Sets the value of the borderTop property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setBorderTop(String value)
	{
		this.borderTop = value;
	}

	/**
	 * Sets the value of the columns property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setColumns(String value)
	{
		this.columns = value;
	}

	/**
	 * Sets the value of the layer property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setLayer(String value)
	{
		this.layer = value;
	}

	/**
	 * Sets the value of the rows property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setRows(String value)
	{
		this.rows = value;
	}

	/**
	 * Sets the value of the x1 property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setX1(String value)
	{
		this.x1 = value;
	}

	/**
	 * Sets the value of the x2 property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setX2(String value)
	{
		this.x2 = value;
	}

	/**
	 * Sets the value of the y1 property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setY1(String value)
	{
		this.y1 = value;
	}

	/**
	 * Sets the value of the y2 property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setY2(String value)
	{
		this.y2 = value;
	}

}
