//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.10.23 at 08:50:01 AM PDT
//

package org.openpnp.model.eagle.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "grid")
public class Grid
{

	@XmlAttribute(name = "distance")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String	distance;
	@XmlAttribute(name = "unitdist")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String	unitdist;
	@XmlAttribute(name = "unit")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String	unit;
	@XmlAttribute(name = "style")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String	style;
	@XmlAttribute(name = "multiple")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String	multiple;
	@XmlAttribute(name = "display")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String	display;
	@XmlAttribute(name = "altdistance")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String	altdistance;
	@XmlAttribute(name = "altunitdist")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String	altunitdist;
	@XmlAttribute(name = "altunit")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String	altunit;

	/**
	 * Gets the value of the altdistance property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getAltdistance()
	{
		return this.altdistance;
	}

	/**
	 * Gets the value of the altunit property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getAltunit()
	{
		return this.altunit;
	}

	/**
	 * Gets the value of the altunitdist property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getAltunitdist()
	{
		return this.altunitdist;
	}

	/**
	 * Gets the value of the display property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getDisplay()
	{
		if (this.display == null)
			return "no";
		else
			return this.display;
	}

	/**
	 * Gets the value of the distance property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getDistance()
	{
		return this.distance;
	}

	/**
	 * Gets the value of the multiple property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getMultiple()
	{
		if (this.multiple == null)
			return "1";
		else
			return this.multiple;
	}

	/**
	 * Gets the value of the style property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getStyle()
	{
		if (this.style == null)
			return "lines";
		else
			return this.style;
	}

	/**
	 * Gets the value of the unit property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getUnit()
	{
		return this.unit;
	}

	/**
	 * Gets the value of the unitdist property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getUnitdist()
	{
		return this.unitdist;
	}

	/**
	 * Sets the value of the altdistance property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setAltdistance(String value)
	{
		this.altdistance = value;
	}

	/**
	 * Sets the value of the altunit property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setAltunit(String value)
	{
		this.altunit = value;
	}

	/**
	 * Sets the value of the altunitdist property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setAltunitdist(String value)
	{
		this.altunitdist = value;
	}

	/**
	 * Sets the value of the display property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setDisplay(String value)
	{
		this.display = value;
	}

	/**
	 * Sets the value of the distance property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setDistance(String value)
	{
		this.distance = value;
	}

	/**
	 * Sets the value of the multiple property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setMultiple(String value)
	{
		this.multiple = value;
	}

	/**
	 * Sets the value of the style property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setStyle(String value)
	{
		this.style = value;
	}

	/**
	 * Sets the value of the unit property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setUnit(String value)
	{
		this.unit = value;
	}

	/**
	 * Sets the value of the unitdist property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setUnitdist(String value)
	{
		this.unitdist = value;
	}

}
