//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.10.23 at 08:50:01 AM PDT
//

package org.openpnp.model.eagle.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder =
{ "description", "ports", "variantdefs", "parts", "sheets" })
@XmlRootElement(name = "module")
public class Module
{

	@XmlAttribute(name = "name", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String		name;
	@XmlAttribute(name = "prefix")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String		prefix;
	@XmlAttribute(name = "dx", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String		dx;
	@XmlAttribute(name = "dy", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String		dy;
	protected Description	description;
	protected Ports			ports;
	protected Variantdefs	variantdefs;
	protected Parts			parts;
	protected Sheets		sheets;

	/**
	 * Gets the value of the description property.
	 * 
	 * @return possible object is {@link Description }
	 */
	public Description getDescription()
	{
		return this.description;
	}

	/**
	 * Gets the value of the dx property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getDx()
	{
		return this.dx;
	}

	/**
	 * Gets the value of the dy property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getDy()
	{
		return this.dy;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getName()
	{
		return this.name;
	}

	/**
	 * Gets the value of the parts property.
	 * 
	 * @return possible object is {@link Parts }
	 */
	public Parts getParts()
	{
		return this.parts;
	}

	/**
	 * Gets the value of the ports property.
	 * 
	 * @return possible object is {@link Ports }
	 */
	public Ports getPorts()
	{
		return this.ports;
	}

	/**
	 * Gets the value of the prefix property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getPrefix()
	{
		if (this.prefix == null)
			return "";
		else
			return this.prefix;
	}

	/**
	 * Gets the value of the sheets property.
	 * 
	 * @return possible object is {@link Sheets }
	 */
	public Sheets getSheets()
	{
		return this.sheets;
	}

	/**
	 * Gets the value of the variantdefs property.
	 * 
	 * @return possible object is {@link Variantdefs }
	 */
	public Variantdefs getVariantdefs()
	{
		return this.variantdefs;
	}

	/**
	 * Sets the value of the description property.
	 * 
	 * @param value
	 *            allowed object is {@link Description }
	 */
	public void setDescription(Description value)
	{
		this.description = value;
	}

	/**
	 * Sets the value of the dx property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setDx(String value)
	{
		this.dx = value;
	}

	/**
	 * Sets the value of the dy property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setDy(String value)
	{
		this.dy = value;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setName(String value)
	{
		this.name = value;
	}

	/**
	 * Sets the value of the parts property.
	 * 
	 * @param value
	 *            allowed object is {@link Parts }
	 */
	public void setParts(Parts value)
	{
		this.parts = value;
	}

	/**
	 * Sets the value of the ports property.
	 * 
	 * @param value
	 *            allowed object is {@link Ports }
	 */
	public void setPorts(Ports value)
	{
		this.ports = value;
	}

	/**
	 * Sets the value of the prefix property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setPrefix(String value)
	{
		this.prefix = value;
	}

	/**
	 * Sets the value of the sheets property.
	 * 
	 * @param value
	 *            allowed object is {@link Sheets }
	 */
	public void setSheets(Sheets value)
	{
		this.sheets = value;
	}

	/**
	 * Sets the value of the variantdefs property.
	 * 
	 * @param value
	 *            allowed object is {@link Variantdefs }
	 */
	public void setVariantdefs(Variantdefs value)
	{
		this.variantdefs = value;
	}

}
