//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.10.23 at 08:50:01 AM PDT
//

package org.openpnp.model.eagle.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder =
{ "description", "plain", "moduleinsts", "instances", "busses", "nets" })
@XmlRootElement(name = "sheet")
public class Sheet
{

	protected Description	description;
	protected Plain			plain;
	protected Moduleinsts	moduleinsts;
	protected Instances		instances;
	protected Busses		busses;
	protected Nets			nets;

	/**
	 * Gets the value of the busses property.
	 * 
	 * @return possible object is {@link Busses }
	 */
	public Busses getBusses()
	{
		return this.busses;
	}

	/**
	 * Gets the value of the description property.
	 * 
	 * @return possible object is {@link Description }
	 */
	public Description getDescription()
	{
		return this.description;
	}

	/**
	 * Gets the value of the instances property.
	 * 
	 * @return possible object is {@link Instances }
	 */
	public Instances getInstances()
	{
		return this.instances;
	}

	/**
	 * Gets the value of the moduleinsts property.
	 * 
	 * @return possible object is {@link Moduleinsts }
	 */
	public Moduleinsts getModuleinsts()
	{
		return this.moduleinsts;
	}

	/**
	 * Gets the value of the nets property.
	 * 
	 * @return possible object is {@link Nets }
	 */
	public Nets getNets()
	{
		return this.nets;
	}

	/**
	 * Gets the value of the plain property.
	 * 
	 * @return possible object is {@link Plain }
	 */
	public Plain getPlain()
	{
		return this.plain;
	}

	/**
	 * Sets the value of the busses property.
	 * 
	 * @param value
	 *            allowed object is {@link Busses }
	 */
	public void setBusses(Busses value)
	{
		this.busses = value;
	}

	/**
	 * Sets the value of the description property.
	 * 
	 * @param value
	 *            allowed object is {@link Description }
	 */
	public void setDescription(Description value)
	{
		this.description = value;
	}

	/**
	 * Sets the value of the instances property.
	 * 
	 * @param value
	 *            allowed object is {@link Instances }
	 */
	public void setInstances(Instances value)
	{
		this.instances = value;
	}

	/**
	 * Sets the value of the moduleinsts property.
	 * 
	 * @param value
	 *            allowed object is {@link Moduleinsts }
	 */
	public void setModuleinsts(Moduleinsts value)
	{
		this.moduleinsts = value;
	}

	/**
	 * Sets the value of the nets property.
	 * 
	 * @param value
	 *            allowed object is {@link Nets }
	 */
	public void setNets(Nets value)
	{
		this.nets = value;
	}

	/**
	 * Sets the value of the plain property.
	 * 
	 * @param value
	 *            allowed object is {@link Plain }
	 */
	public void setPlain(Plain value)
	{
		this.plain = value;
	}

}
