//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.10.23 at 08:50:01 AM PDT
//

package org.openpnp.model.eagle.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "wire")
public class Wire
{

	@XmlAttribute(name = "x1", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String	x1;
	@XmlAttribute(name = "y1", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String	y1;
	@XmlAttribute(name = "x2", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String	x2;
	@XmlAttribute(name = "y2", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String	y2;
	@XmlAttribute(name = "width", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String	width;
	@XmlAttribute(name = "layer", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String	layer;
	@XmlAttribute(name = "extent")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String	extent;
	@XmlAttribute(name = "style")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String	style;
	@XmlAttribute(name = "curve")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String	curve;
	@XmlAttribute(name = "cap")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String	cap;

	/**
	 * Gets the value of the cap property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getCap()
	{
		if (this.cap == null)
			return "round";
		else
			return this.cap;
	}

	/**
	 * Gets the value of the curve property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getCurve()
	{
		if (this.curve == null)
			return "0";
		else
			return this.curve;
	}

	/**
	 * Gets the value of the extent property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getExtent()
	{
		return this.extent;
	}

	/**
	 * Gets the value of the layer property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getLayer()
	{
		return this.layer;
	}

	/**
	 * Gets the value of the style property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getStyle()
	{
		if (this.style == null)
			return "continuous";
		else
			return this.style;
	}

	/**
	 * Gets the value of the width property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getWidth()
	{
		return this.width;
	}

	/**
	 * Gets the value of the x1 property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getX1()
	{
		return this.x1;
	}

	/**
	 * Gets the value of the x2 property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getX2()
	{
		return this.x2;
	}

	/**
	 * Gets the value of the y1 property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getY1()
	{
		return this.y1;
	}

	/**
	 * Gets the value of the y2 property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getY2()
	{
		return this.y2;
	}

	/**
	 * Sets the value of the cap property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setCap(String value)
	{
		this.cap = value;
	}

	/**
	 * Sets the value of the curve property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setCurve(String value)
	{
		this.curve = value;
	}

	/**
	 * Sets the value of the extent property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setExtent(String value)
	{
		this.extent = value;
	}

	/**
	 * Sets the value of the layer property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setLayer(String value)
	{
		this.layer = value;
	}

	/**
	 * Sets the value of the style property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setStyle(String value)
	{
		this.style = value;
	}

	/**
	 * Sets the value of the width property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setWidth(String value)
	{
		this.width = value;
	}

	/**
	 * Sets the value of the x1 property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setX1(String value)
	{
		this.x1 = value;
	}

	/**
	 * Sets the value of the x2 property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setX2(String value)
	{
		this.x2 = value;
	}

	/**
	 * Sets the value of the y1 property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setY1(String value)
	{
		this.y1 = value;
	}

	/**
	 * Sets the value of the y2 property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setY2(String value)
	{
		this.y2 = value;
	}

}
